name:                ini
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- parsers
- trifecta
- directory
- cmdargs
- containers
- filepath

library:
  source-dirs: src

executables:
  ini-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ini

tests:
  ini-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ini
    - hspec
    - bytestring
    - raw-strings-qq
