name:                haskellbook
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- bytestring
- text
- scientific
- time
- transformers
- random
- parsers
- trifecta
- aeson
- criterion
- containers
- vector
- dlist
- raw-strings-qq

library:
  source-dirs: src

tests:
  haskellbook-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskellbook
    - hspec
    - QuickCheck
    - HUnit
    - checkers
