name:                cipher
version:             0.0.0.1

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  cipher-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cipher
    - cmdargs

tests:
  cipher-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cipher
    - hspec
    - QuickCheck
