name:                finger
version:             0.1.0.0
github:              "githubuser/fingerd"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/githubuser/fingerd#readme>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- network
- sqlite-simple
- cmdargs
- raw-strings-qq

library:
  source-dirs: src

executables:
  fingerd:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -main-is Main
    dependencies:
    - finger

  debug:
    main:                Debug.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -main-is Debug
    dependencies:
    - finger

  useradd:
    main:                Useradd.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -main-is Useradd
    dependencies:
    - finger